[project]
name = "dotfiles"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "epilatow-repo-shared",
    "pytest>=9.0.3",
]

[tool.uv.sources]
epilatow-repo-shared = { git = "https://github.com/epilatow/repo-shared", rev = "578b864ed64b4de843897e2ae6584998449bf8be" }

[tool.pytest.ini_options]
testpaths = ["_repo_shared/tests"]
