# scrollback / copy-mode defaults
set -g mode-keys vi
set -g mouse on
set -g default-terminal "tmux-256color"
set -g history-limit 50000

# Enable extended keyboard escape sequences
set -g extended-keys on
set -g extended-keys-format csi-u

# Don't exit scrollback mode after making a mouse selection.
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-selection-no-clear

# Add a config reload command: ^BR
bind R source-file ~/.tmux.conf \; display-message "tmux config reloaded"
